// One-time testnet setup: creates the Remitt treasury account, funds it via
// friendbot, opens a trustline to Circle's testnet USDC, and writes
// src/lib/stellar-config.ts.
//
// After running, fund the treasury with USDC at https://faucet.circle.com
// (select Stellar testnet, paste the treasury address).
//
// Run: node scripts/setup-testnet.mjs
import { Keypair, Horizon, TransactionBuilder, Networks, Operation, Asset, BASE_FEE } from '@stellar/stellar-sdk';
import { writeFileSync } from 'node:fs';

// Circle's official USDC issuer on Stellar testnet
const USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5';

const server = new Horizon.Server('https://horizon-testnet.stellar.org');

async function friendbot(pub) {
  const res = await fetch(`https://friendbot.stellar.org?addr=${pub}`);
  if (!res.ok) throw new Error(`friendbot failed for ${pub}: ${await res.text()}`);
}

const treasury = Keypair.random();
console.log('Treasury:', treasury.publicKey());

console.log('Funding via friendbot...');
await friendbot(treasury.publicKey());

const USDC = new Asset('USDC', USDC_ISSUER);

console.log('Opening USDC trustline...');
const account = await server.loadAccount(treasury.publicKey());
const tx = new TransactionBuilder(account, { fee: BASE_FEE, networkPassphrase: Networks.TESTNET })
  .addOperation(Operation.changeTrust({ asset: USDC }))
  .setTimeout(60)
  .build();
tx.sign(treasury);
await server.submitTransaction(tx);

const config = `// Generated by scripts/setup-testnet.mjs — testnet demo config.
// The treasury secret is embedded for demo purposes only (it sponsors new
// account creation and settles cash-in/out). Never do this in prod.
export const HORIZON_URL = 'https://horizon-testnet.stellar.org';
export const NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
export const USDC_CODE = 'USDC';
export const USDC_ISSUER = '${USDC_ISSUER}';
export const TREASURY_PUBLIC = '${treasury.publicKey()}';
export const TREASURY_SECRET = '${treasury.secret()}';
`;
writeFileSync(new URL('../src/lib/stellar-config.ts', import.meta.url), config);
console.log('Wrote src/lib/stellar-config.ts');
console.log('');
console.log('NEXT STEP: fund the treasury with USDC at https://faucet.circle.com');
console.log('  → Network: Stellar Testnet, address:', treasury.publicKey());
