// Regenerates src/lib/stellar-config.ts for the requested network. Kept as a
// flat literal-const file (not a runtime if/else) on purpose: several scripts
// (fund-treasury.mjs, send-yield-digest.mjs, setup-channel-accounts.mjs, the
// custody-2of3/ test scripts, etc.) parse it with a regex expecting
// `NAME = 'value'` — a computed/ternary export would break all of them. This
// script is the single source of truth for both networks' public values;
// everything else keeps reading stellar-config.ts exactly as before.
//
// Run (from packages/app):
//   node scripts/switch-network.mjs testnet
//   node scripts/switch-network.mjs mainnet
//
// NOTE: this does NOT touch the treasury secret or fund/create anything
// on-chain — it only rewrites the public config file. Switching to mainnet
// requires TREASURY_PUBLIC below to already be a real, funded mainnet
// account (see [[phase1-mainnet-beta-checklist]] — key rotation is a
// separate, deliberate step, not something this script should do casually).
import { writeFileSync } from 'node:fs';

const NETWORKS = {
  testnet: {
    HORIZON_URL: 'https://horizon-testnet.stellar.org',
    NETWORK_PASSPHRASE: 'Test SDF Network ; September 2015',
    USDC_ISSUER: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
    TREASURY_PUBLIC: 'GAACQW3PRNKQQMHX35Q6J2UQNC5NEB26STNUI5SG3TFSHTEDWCXVXYJ6',
    BLEND_POOL_ID: 'CAPBMXIQTICKWFPWFDJWMAKBXBPJZUKLNONQH3MLPLLBKQ643CYN5PRW',
  },
  mainnet: {
    HORIZON_URL: 'https://horizon.stellar.org',
    NETWORK_PASSPHRASE: 'Public Global Stellar Network ; September 2015',
    USDC_ISSUER: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN', // Circle's official mainnet USDC issuer
    // TODO: fill in once the mainnet treasury key exists (HSM + fresh-key
    // rotation blocker — not yet done as of this script's writing).
    TREASURY_PUBLIC: '',
    BLEND_POOL_ID: 'CAJJZSGMMM3PD7N33TAPHGBUGTB43OC73HVIK2L2G6BNGGGYOSSYBXBD',
  },
};

const network = process.argv[2];
if (network !== 'testnet' && network !== 'mainnet') {
  console.error('Usage: node scripts/switch-network.mjs <testnet|mainnet>');
  process.exit(1);
}

const cfg = NETWORKS[network];
if (network === 'mainnet' && !cfg.TREASURY_PUBLIC) {
  console.error(
    'Refusing to switch to mainnet: TREASURY_PUBLIC is not set yet in this script.\n' +
      'Fill it in with the real, rotated mainnet treasury address first (see NETWORKS.mainnet above).',
  );
  process.exit(1);
}

const config = `// Generated by scripts/switch-network.mjs (network: ${network}).
// PUBLIC values only. The treasury SECRET intentionally does NOT live here: it
// would ship in the Expo bundle (Metro bundles whole imported modules), so it
// lives in the gitignored, app-never-imports-it scripts/treasury-secret.mjs
// instead. The app doesn't need it — delivery/sponsorship are signed server-side
// (Edge Functions). See onramp-build-plan / mainnet hard wall #1.
export const HORIZON_URL = '${cfg.HORIZON_URL}';
export const NETWORK_PASSPHRASE = '${cfg.NETWORK_PASSPHRASE}';
export const USDC_CODE = 'USDC';
export const USDC_ISSUER = '${cfg.USDC_ISSUER}';
export const TREASURY_PUBLIC = '${cfg.TREASURY_PUBLIC}';
export const BLEND_POOL_ID = '${cfg.BLEND_POOL_ID}';
`;
writeFileSync(new URL('../src/lib/stellar-config.ts', import.meta.url), config);
console.log(`Wrote src/lib/stellar-config.ts for ${network}.`);
console.log('Remember: this is a full rebuild boundary for the app (Metro bundles it in) — rebuild/redeploy after switching.');
